### PR TITLE
Getopt return

### PR DESCRIPTION
**Pull request by jberger**
Proposed for implementation of #1343. Calling for a vote from @mojolicious/core.

### CODE REVIEW

**Comment by jberger** [comment]
Le sigh. Calling for a vote (in a comment) @mojolicious/core

**Comment by jhthorsen** [comment]
What’s the big difference between this change and https://github.com/mojolicious/mojo/pull/1343?

**Comment by kraih** [comment]
I don't really care about this PR and therefore vote neutral.

**Comment by marcusramberg** [comment]
@jhthorsen As @jberger said in the pr you linked to: "I've made a branch that takes these commits, adds one to normalize the tests, and rebases against master (as of this comment)". I'm also 👍so this PR passed.

**Pull request merged**
