### PR TITLE
Fix typo URL in travis-ci Build Status

### PR DESCRIPTION
**Pull request by yusrideb**
### Summary
Fix a typo of URL in Link Build Status Travis-CI

### Motivation
Correctness

### CODE REVIEW

**Comment by jhthorsen** [comment]
Calling for a vote @mojolicious/core.

I'm 👍on this.

**Comment by kraih** [comment]
To be clear, just the URL fix would have been fine with me, that's a bug.

**Comment by yusrideb** [comment]
I try to rollback commit caebae3

**Comment by yusrideb** [comment]
> I'll have to vote  on this because of the lonely typo fix in a separate commit. We specifically ask in the [guide](https://mojolicious.org/perldoc/Mojolicious/Guides/Contributing) not to do that. If you want to spell check all of Mojo that's fine, but no commits just for one typo.

@kraih, Thank you for reminding me.

Now, I have found 1 more typo in [Mojolicious::Plugin::DefaultHelper](https://github.com/mojolicious/mojo/blob/master/lib/Mojolicious/Plugin/DefaultHelpers.pm#L744).
So far, I have found 2 typos : 
- [Mojolicious::Plugin::DefaultHelper](https://github.com/mojolicious/mojo/blob/master/lib/Mojolicious/Plugin/DefaultHelpers.pm#L744) -> Line 744
- [Test::Mojo](https://github.com/mojolicious/mojo/blob/master/lib/Test/Mojo.pm#L501) -> Line 501

If permitted, I will try to fix it, and please give instructions for the next step. Thank you before

**Comment by kraih** [comment]
The commit message does not sound like proper english.

**Comment by kraih** [comment]
Sorry, but the wait got a bit much.

**Comment by yusrideb** [comment]
> The commit message does not sound like proper english.

Thank you for reminding me. And thanks for all.

**Pull request closed without merging**
