### PR TITLE
convert t/mojolicious/twinkle_lite_app.t to use subtests

### PR DESCRIPTION
**Pull request by markogrady1**
### Summary
convert `t/mojolicious/twinkle_lite_app.t` to use subtests

### Motivation
wanting to contribute to the conversion to subtests

### References
discussed in #1520

### CODE REVIEW

**Comment by kraih** [comment]
Reviewers please double check perltidy.

**Review by jhthorsen — DISMISSED** [review]
I think perltidy butchered some of these lines, but it looks correct to me.

**Review by kraih — CHANGES_REQUESTED** [review]
Please rebase to master for perltidy check.

**Review by kraih — APPROVED** [review]

**Review by jhthorsen — APPROVED** [review]
LGMT

**Pull request merged**
