### PR TITLE
do not strengthen weak promise callback arguments

### PR DESCRIPTION
**Pull request by karenetheridge**
### Summary
Arguments to promise callback subs are weakened as they are copied, if the originals were weak.

### Motivation
Otherwise, memory leaks occur when defining callback subs that close over things like `$app`, `$ua` etc.

### References
Briefly discussed on \#mojo today.

### CODE REVIEW

**Comment by karenetheridge** [comment]
My first attempt at a fix did not work -- there is more that needs to be done lower down. I have followed the code down into `$self->ioloop->next_tick(..)` and then more needs to be done in there as well.

**Comment by jhthorsen** [comment]
Do you have a test that actually shows that the objects leak? There's many places in mojo where they appear to leak, but everything is cleaned up once the promise/delay is done doing what it's supposed to do.

**Comment by kraih** [comment]
This pull request appears stale and broken, so i'm closing it instead of calling for a vote. Please feel free to resubmit a more complete patch.

**Comment by karenetheridge** [comment]
This wasn't a patch proposal, but a demonstration of a problem, which @jberger asked me to submit.

**Pull request closed without merging**
