### PR TITLE
Add log alias

### PR DESCRIPTION
**Pull request by marcusramberg**
Add a log alias helper to Mojolicious::Plugin::DefaultHelpers,
and update guides and helpers to use it

Logging often happens from the controller, and this saves you from
repetitive $c->app->log calls.

This is a updated version of #1270

### CODE REVIEW

**Comment by kraih** [comment]
Don't use `$c->log->*` in core Mojo code, it's much much slower than `$c->helpers->log->*`, and can break if someone has a log method in their controller.

**Comment by marcusramberg** [comment]
> Don't use `$c->log->*` in core Mojo code, it's much much slower than `$c->helpers->log->*`, and can break if someone has a log method in their controller.

Good point. Made more sense when it was just a shortcut instead of a helper. Pushed a fixup commit to remove that part now.

**Comment by kraih** [comment]
My vote will be neutral on this. Only reason i can think of against it would be the possibility of us wanting to use a log helper in the future for logging with request ids.

**Comment by jberger** [comment]
I've always wanted the controller's logger to be a little smarter. I'd like it to have things like contextual information, request id and other things. This would be convenient but limit that future option. I'm pretty sure I discussed this at the hack day in Oslo. Anyway, that said, if the convenience is the pure benefit, I wont block it. Guess I'm neutral on the assumption that (and @kraih just posted) that the idea of per-controller logging is at least considered before accepting this proposal.

**Comment by jhthorsen** [comment]
@jberger: I'm not sure if I follow. Could you tell a bit more about what you would add to the log helper to get what you want? An example log line might be enough to get me up to speed.

**Comment by marcusramberg** [comment]
I guess this helper could later be extended to give the logger more
metadata if it supports it?

**Comment by kraih** [comment]
We might want to use nested helpers like `log.debug` for logging with request id.

**Comment by kraih** [comment]
Looks like the discussion went stale. Given the arguments we've collected so far, i'll have to give this a 👎.

**Comment by kraih** [comment]
Since this proposal did not reach the required votes, i'll close it for now.

**Pull request closed without merging**
