### PR TITLE
Substitution replaced with transliteration

### PR DESCRIPTION
**Pull request by k-mx**
### Summary
Transliteration is 10x faster and often more expressive

### Motivation
Of course changes are not necessary, but having faster operator inside nested loops is not a bad idea? :)

Good luck!

### CODE REVIEW

**Comment by k-mx** [comment]
1. No performance gain for Mojo::DOM::CSS, so I will undo this change.
2. Changes in Mojo::IOLoop::Server is about readability. I think with transliteration it looks nicer
3. tablify works about 5-7% faster with transliteration, but of course, it is not slow in existing variation. I can provide benchmark for tablify today, when I get home.

I just thought, that when we want to replace group of characters, transliteration is literally instrument for that. That's the main reason, not performance.

**Comment by jhthorsen** [comment]
I'm indifferent to this change, but I also don't see the harm. 😐

**Comment by kraih** [comment]
Calling for a vote @mojolicious/core.

**Comment by marcusramberg** [comment]
:+1:

**Comment by kraih** [comment]
This PR passed the vote.

**Pull request merged**
