### PR TITLE
Restore promise map

### PR DESCRIPTION
**Pull request by jberger**
### Summary
Restore Mojo::Promise::map and improve where there were concerns

### Motivation
Because it was mostly ok, just needed some tweaks, and it is very useful

I have improved the test case to fail when the $proto promise wasn't cloned, however, I have then removed the $proto promise all together as an attempt to prevent warnings as we attempt to warn on unhandled rejected promises.

### CODE REVIEW

**Comment by jberger** [comment]
Note that it might be easier to review the comparison from before map was removed (and is restored in this PR): https://github.com/mojolicious/mojo/compare/3ca458038..restore_promise_map

**Comment by jberger** [comment]
I'll also note that the weaken on the $loop is only needed because we close over $loop to return a rejection [here](https://github.com/mojolicious/mojo/compare/3ca458038..restore_promise_map#diff-27bd5e0ace07b04f2ba7f5e7ec0115c1R80). If "die" would work to "rethrow" the error then that weaken could be removed.

**Comment by kraih** [comment]
It does not look good to me, `weaken $loop` is  a pretty ugly hack.

**Comment by jberger** [comment]
Closing as superseded by a1f6d8a66d068b9c269efcf0bfb6e25bfd5a1d9f

**Pull request closed without merging**
