### PR TITLE
convert t/mojolicious/ojo.t to use subtests

### PR DESCRIPTION
**Pull request by markogrady1**
### Summary
Subtests for ojo

### Motivation
as discussed in #1520
Want to contribute :)

### CODE REVIEW

**Comment by kraih** [comment]
You didn't perltidy the test.

**Comment by markogrady1** [comment]
perltidied version incoming :)

**Comment by kraih** [comment]
We always squash commits.

**Review by kraih — APPROVED** [review]

**Review by kraih — CHANGES_REQUESTED** [review]
Use a proper commit message.

**Review by kraih — APPROVED** [review]

**Review by jhthorsen — APPROVED** [review]
LGTM 👍

**Comment by kraih** [comment]
You did not use the latest version of perltidy. https://github.com/mojolicious/mojo/compare/22836c095dfb...e8311131783a

**Pull request merged**
