### PR TITLE
use the new perltidy

### PR DESCRIPTION
**Pull request by jberger**
update the codebase for the new perltidy so that PRs don't fail the perltidy test.

### CODE REVIEW

**Comment by jberger** [comment]
@mojolicious/maintainers please review this

**Review by kraih — APPROVED** [review]

**Comment by karenetheridge** [comment]
Why not instead update the .perltidyrc so the same preferences are maintained, and to keep the diff to a minimum?

**Review by jhthorsen — APPROVED** [review]
I hope perltidy doesn’t revert the changes 😃

**Comment by marcusramberg** [comment]
Afaict these changes are for the better.

**Pull request merged**
