### PR TITLE
Delay app log stringification

### PR DESCRIPTION
**Pull request by jrubinator**
Edit: Deleted.

### CODE REVIEW

**Comment by kraih** [comment]
You pasted the logs of a conversation that included me without permission.

**Comment by jrubinator** [comment]
@kraih - apologies, I must have misunderstood what was being requested by the template:
```
### References
LIST RELEVANT ISSUES, PULL REQUESTS AND IRC/MAILING-LIST DISCUSSIONS HERE
```

Does IRC DISCUSSION just mean to mention that there _was_ an IRC discussion?

**Comment by kraih** [comment]
Yes, logging our IRC channel is strictly forbidden.

**Comment by jrubinator** [comment]
Very sorry - I was completely unaware. I see that at the top of the IRC channel now that I'm looking for it :( I feel like a jerk.

Do you think it would be worth updating https://docs.mojolicious.org/Mojolicious/Guides/Contributing#CODE-OF-CONDUCT to be explicit about that as well?

**Comment by kraih** [comment]
It was an honest mistake, that's allright, please just don't do it again.

**Pull request closed without merging**
